name: Slack
version: 1.5.0
description: Link your server to Slack!
author: CircuitSoft
authors: [Janmm14, LaxWasHere, it3d, Davy]
website: https://circuitsoft.us

main: org.circuitsoft.slack.bukkit.SlackBukkit

permissions:
    slack.hide.command:
        description: Does not post commands you do to Slack.
        default: false
    slack.command:
        description: Allows you to send messages and reload Slack using /slack.
        default: op
    slack.hide.login:
        description: Does not post to Slack when you login.
        default: false
    slack.hide.logout:
        description: Does not post to Slack when you logout.
        default: false
    slack.hide.chat:
        description: Does not post your chats to Slack.
        default: false
commands:
    slack:
        description: Help command for Slack.
        permission: slack.command
        usage: Do /slack for a list of Slack's commands.
